---
- hosts: win
  tasks:
    - name: deploy release folder
      win_copy:
          src: Release/Package/
          dest: C:\temp\FacultyPortal\
    - name: deploy build folder
      win_copy:
          src: build/
          dest: C:\temp\FacultyPortal\api\
    - name: deploy development folder
      win_copy:
          src: development/
          dest: C:\temp\FacultyPortal\api\